### ISSUE TITLE
Text mode font gets clipped (Fedora 19, xfce)

### ISSUE THREAD

**Issue by timothy-kim** [paralect/robomongo#443]
In text mode, the font is rendered too big but the line height isn't adjusted accordingly. So the the text is clipped, which makes the editor unusable.

Screenshot:

![screenshot](http://i.imgur.com/FxI1ugY.png)

Robomongo Install:

    Name        : robomongo
    Arch        : x86_64
    Version     : 0.8.4
    Release     : 1
    From repo   : /robomongo-0.8.4-x86_64

OS:

    Fedora 19 with xfce 4.10

**Comment by stennie** [comment]
Closing as a duplicate of #649, which I believe will address the underlying issue of incorrect text height calculations.

**Comment by stennie** [comment]
Just rechecked, and it looks like the upstream bug [QTBUG-32254](https://bugreports.qt.io/browse/QTBUG-32254) has been fixed in Qt 5.4.0!

Reopening as there's hope this might be fixed if we retest with newer Qt :)

**Comment by ALeschinsky** [comment]
Have the same problem on Linux Mint.

**Comment by anorsich** [comment]
@stennie @ALeschinsky @tiriana  Latest release of Robomongo ([0.9.0](http://blog.robomongo.org/robomongo-0-9-0-rc3-released/)) based on QT 5.5. Could you check if that issue already resolved?

**Comment by ALeschinsky** [comment]
Unfortunately, same thing: 
![image](https://cloud.githubusercontent.com/assets/2109420/12687787/0291ced6-c6a0-11e5-8de1-bec43d28a80a.png)

**Comment by anorsich** [comment]
@ALeschinsky Could you also try [a version](http://download.robomongo.org/0.9.0-rc3/linux/centos/robomongo-0.9.0-rc3-linux-x86_64-0476204.tar.gz), built on Centos and let us know if it worked for you.

**Comment by ALeschinsky** [comment]
Looks exactly the same. Feel free to add logging or anything, I'll be happy to help. And I'd love to use Robomongo, too.

**Comment by juliashibalko** [comment]
Hi guys! Could you please check issue with Robomongo 0.9.0-RC10 if possible? We implemented better HiDPI support there and transited to Qt5.7. So I hope it will solve the problem.
Please see download site https://robomongo.org/download and feature list http://blog.robomongo.org/robomongo-rc10/

**Comment by vcampitelli** [comment]
Hi there! I'm using Robomongo 0.9.0 and the problem still occurs =(

I'm using Debian 8.6 (GNOME Shell 3.14.4). And I do have Infinality patch installed.

![Screenshot](https://cloud.githubusercontent.com/assets/1877191/21692623/d779bd1c-d364-11e6-86c8-cf28224e056d.png)

**Comment by vcampitelli** [comment]
Hi! I'm using Robomongo 0.9.0 and the error still occurs =(

When I open a new window, the following error appears (3 times):

`QWidget::setMinimumSize: (/Robomongo::QueryWidget::CustomDockWidget) Negative sizes (0,-1) are not possible`


OS: Debian 8.6
Window manager: Gnome Shell 3.14.4
Using Infinality

![selection_008](https://cloud.githubusercontent.com/assets/1877191/21692943/3415de92-d366-11e6-9faf-d78af1b09109.png)

**Comment by simsekgokhan** [comment]
Hi @vcampitelli , thanks for reporting the problem with details.
Warnings that you are getting is not related to your issue.

Initial comments will be that Robomongo uses Qt and there are some known GUI related compatibility issue between Qt and some linux distributions. Currently, we see that Qt has better support for OSX and Windows. So clipped text issue also seems like Qt compatibility issue. But of course, we can only be sure after more investigation.

For now, as a workaround solution, can you change the font size and restart Robomongo? 
This should change the fonts in query tabs and results window for text mode.

~/.config/robomongo/0.9/robomongo.json
` "textFontPointSize" : 10,`

I hope it will work.

**Comment by ALeschinsky** [comment]
Here's how it looks for me:

![image](https://cloud.githubusercontent.com/assets/2109420/21719654/eb681282-d3ec-11e6-9bc7-f05c981405fc.png)

Let me know if I can help with a configuration file dump or anything else.
